server:
  port: 80
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/publicactive
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
upload:
  directory:
    path: D:/DevelopTools/Code/uu_publice/src/main/resources/static/images